version: '3.9'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 3000:3000
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=materialize
      - CUBEJS_DB_HOST=materialized
      - CUBEJS_DB_PORT=6875
      - CUBEJS_DB_NAME=materialize
      - CUBEJS_DB_USER=materialize
      - CUBEJS_API_SECRET=SECRET
      - CUBEJS_WEB_SOCKETS=true
    volumes:
      - .:/cube/conf
